/* eslint-disable import/no-extraneous-dependencies */
import fg from "fast-glob";
import fs from "fs";

const entries = fg.sync(["roms/**/*.{gb,gbc}"]);

const roms = entries.map((e) => e.replace("roms/", "")).sort();

const PATH = "../roms";

function generateOutput(items) {
	const imports = items.map((item, i) => {
		const key = `rom${i}`;
		return {
			import: `import ${key} from '${PATH}/${item}'`,
			key,
			name: item,
		};
	});
	const importStatements = imports.map((item) => item.import).join("\n");
	const exportObj = imports
		.map((item) => `{ name: '${item.name}', url: ${item.key} }`)
		.join(",");
	const exportStatement = `export const roms = [${exportObj}]`;

	return `/* eslint-disable simple-import-sort/imports */\n// AUTOGENERATED\n${importStatements}\n\n${exportStatement}`;
}

// TODO format with biome
const out = generateOutput(roms)

fs.writeFileSync(`${import.meta.dirname}/browser/romsList.ts`, out);
