allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - glob@10.5.0
  - minimatch@9.0.6 || 9.0.7 || 10.2.3
  - rollup@4.59.0
  - svgo@3.3.3
  - tar@7.5.10 || 7.5.11
  - brace-expansion@2.0.3 || 5.0.5 || 5.0.6
  - picomatch@2.3.2 || 4.0.4
  - yaml@2.8.3
  - vite@7.3.2
  - postcss@8.5.10 || 8.5.29
  - react-dom@19.2.7
  - react-is@19.2.7
  - react@19.2.7
  - '@vitejs/plugin-react@6.1.2'
