[package]
name = "integration-tests"
version = "0.1.0"
edition = "2018"

[dependencies]
gb = { path = "../gb" }
glob = "0.3.0"
regex = "1.4.3"
chrono = "0.4.19"
futures = { version = "0.3.*" }
tokio = { version = "1.3.0", features = ["full"] }
image = "0.23.14"
pixelmatch = "0.1.0"