[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
gb = { path = "../gb" }
glob = "0.3.1"
regex = "1.8.1"
chrono = "0.4.24"
futures = "0.3.28"
tokio = { version = "1.28.1", features = ["full"] }
image = "0.24.6"
pixelmatch = "0.1.0"