[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
gb = { path = "../gb" }
glob = "0.3.0"
regex = "1.7.0"
chrono = "0.4.23"
futures = "0.3.25"
tokio = { version = "1.23.0", features = ["full"] }
image = "0.24.5"
pixelmatch = "0.1.0"