[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
gb = { path = "../gb" }
glob = "0.3.0"
regex = "1.5.6"
chrono = "0.4.19"
futures = "0.3.21"
tokio = { version = "1.18.1", features = ["full"] }
image = "0.24.2"
pixelmatch = "0.1.0"