[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
gb = { path = "../gb" }
glob = "0.3.1"
regex = "1.10.3"
chrono = "0.4.33"
futures = "0.3.30"
tokio = { version = "1.36.0", features = ["full"] }
image = "0.25.2"
pixelmatch = "0.1.0"
