name: github-pages

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v1

      - name: Setup wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'

      # https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Installing Dependencies
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - name: Build WASM
        run: |
          pnpm run build:gb 
          pnpm run build:debugger

      - name: Validate frontend
        run: pnpm run validate

      - name: Building App
        run: |
          node generateRomsList.js
          USE_HASH_ROUTER=true pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
