name: github-pages

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: hecrj/setup-rust-action@v2

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Setup wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build WASM + list of ROMs
        run: |
          pnpm run build:gb 
          pnpm run build:debugger
          node generateRomsList.js

      - name: Validate frontend
        run: pnpm run validate

      - name: Building App
        run: USE_HASH_ROUTER=true pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
