[package]
name = "desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
gb = { path = "../gb" }

log = "0.4.17"
sdl2 = { version = "0.35.2", features = [ "bundled", "static-link" ] }
env_logger = "0.10.0"
