[package]
name = "desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
gb = { path = "../gb" }

log = "0.4.22"
sdl2 = { version = "0.37.0", features = ["bundled", "static-link"] }
env_logger = "0.11.5"
